service: standard-cv-frontend

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

plugins:
  - serverless-finch

custom:
  client:
    bucketName: standard-cv-frontend  # Cambia al nombre de tu bucket S3
    distributionFolder: dist  # Carpeta donde Vite genera el build
    region: us-east-1  # Asegúrate de que la región esté definida
    distributionIdKey: EEU042QWEANA9  # Si usas CloudFront
    acl: public-read  # Puedes descomentar si necesitas ACLs


resources:
  Resources:
    StaticWebsiteBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: standard-cv-frontend
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false

    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - DomainName: !GetAtt StaticWebsiteBucket.DomainName
              Id: S3-StaticWebsite
              S3OriginConfig:
                OriginAccessIdentity: ""
          Enabled: true
          DefaultRootObject: index.html
          DefaultCacheBehavior:
            TargetOriginId: S3-StaticWebsite
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
            CachedMethods:
              - GET
              - HEAD
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
            MinTTL: 3600  # Tiempo mínimo de caché (ajusta si lo necesitas)

    StaticWebsiteBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref StaticWebsiteBucket
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal: "*"
              Action: "s3:GetObject"
              Resource: "arn:aws:s3:::standard-cv-frontend/*"